# networks:
#   traefik_public:
#     external: true

services:
#   traefik:
#     image: traefik:3.5.0
#     command:
#       - --entrypoints.web.address=:80
#       - --providers.docker=true
#       - --providers.docker.exposedbydefault=false
#       - --providers.docker.endpoint=tcp://socket_proxy:2375
#       - --providers.docker.network=traefik_public
#       - --log.level=info
#     ports:
#       - 80:80
#     restart: unless-stopped

  backend:
    build: ./server/node_server
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./server/.env

  model:
    build: ./server/model
    ports:
      - '5000:5000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'

  db:
    image: mysql:latest
    env_file:
      - ./server/.env
    volumes:
    - mysql_data:/var/lib/mysql
    - ./server/encryption.sql:/docker-entrypoint-initdb.d/encryption.sql

volumes:
  mysql_data: