services:
  backend:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Linguistic_Pro03
      MYSQL_DATABASE: encrypt
      MYSQL_HOST: db
    # What
    volumes:
    - mysql_data:/var/lib/mysql
    - ./server/encryption.sql:/docker-entrypoint-initdb.d/encryption.sql

volumes:
  mysql_data: